export const companyReportingLine = [
  { id: 1, title: "Product Manager" },
  { id: 2, title: "Associate Product Manager" },
  { id: 3, title: "HR Manager" },
  { id: 4, title: "HR Associate" },
  { id: 5, title: "HR Executive" },
  { id: 6, title: "HR Intern" },
  { id: 7, title: "Lead Developer" },
  { id: 8, title: "Senior Front End Developer" },
  { id: 9, title: "Frontend Developer" },
  { id: 10, title: "Development Intern" },
  { id: 11, title: "Senior Backend Developer" },
  { id: 12, title: "Backend Developer" },
  { id: 13, title: "Laravel Developer" },
  { id: 14, title: "Senior Laravel Developer" },
  { id: 15, title: "Mobile Application Developer" },
  { id: 16, title: "Lead Content Writer" },
  { id: 17, title: "Senior Content Writer" },
  { id: 18, title: "Junior Content Writer" },
  { id: 19, title: "SEO Team Lead" },
  { id: 20, title: "SEO Executive" },
  { id: 21, title: "Junior SEO Executive" },
  { id: 22, title: "Quality Assurance Lead" },
  { id: 23, title: "Software Quality Assurance Executive" },
  { id: 24, title: "Junior SQA" },
  { id: 25, title: "Performance Marketing Manager" },
  { id: 26, title: "Performance Marketing Associate" },
  { id: 27, title: "Senior Product Designer" },
  { id: 28, title: "Product Designer" },
  { id: 29, title: "UI/UX Designer" },
  { id: 30, title: "Graphic Designer" },
  { id: 31, title: "Social Media Manager" },
  { id: 32, title: "PR Executive" },
  { id: 33, title: "Email Marketing Specialist" },
  { id: 34, title: "Email Marketing Associate" },
  { id: 35, title: "Sales Manager" },
  { id: 36, title: "Sales Executive" },
  { id: 37, title: "Inbound Sales Executive" },
  { id: 38, title: "Outbound Sales Executive" },
  { id: 39, title: "After-Sales Executive" },
  { id: 40, title: "Business Development Executive" },
  { id: 41, title: "Senior Data Entry Operator" },
  { id: 42, title: "Data Entry Operator" },
  { id: 43, title: "Admin Executive" },
  { id: 44, title: "Office Boy" },
  { id: 45, title: "Sweeper" },
  { id: 46, title: "Marketing Executive" },
  { id: 47, title: "Video Editor" },
  { id: 48, title: "Videographer" },
  { id: 49, title: "Content Creator" },
  { id: 50, title: "CEO" },
];
