<template>
  <v-row>
    <v-col cols="12"><v-card class="performance-hero" color="secondary"><v-card-text class="d-flex align-center justify-space-between flex-wrap ga-4 pa-6"><div><div class="text-overline opacity-70">Performance workspace</div><div class="text-h4 font-weight-bold">Employee Performance</div><div class="text-body-1 text-medium-emphasis">Record weighted KPI outcomes and turn them into clear review conversations.</div></div><div class="d-flex align-center ga-5"><div class="text-right"><div class="text-h5 font-weight-bold">{{ completedCount }}</div><div class="text-caption text-medium-emphasis">completed reviews</div></div><v-btn color="primary" prepend-icon="mdi-clipboard-plus-outline" :disabled="!activeKpis.length" @click="openReview()">New review</v-btn></div></v-card-text></v-card></v-col>
    <v-col v-if="!employeeStore.kpis.length" cols="12"><v-alert type="info" variant="tonal">Create active KPIs in the KPI Library before starting a review.<template #append><v-btn variant="text" to="/employees/kpis">Open KPI Library</v-btn></template></v-alert></v-col>
    <v-col cols="12" md="4"><v-select v-model="filters.employeeid" :items="employeeOptions" item-title="title" item-value="value" label="Employee" variant="outlined" density="compact" clearable hide-details /></v-col>
    <v-col cols="12" md="3"><v-select v-model="filters.department" :items="departments" label="Department" variant="outlined" density="compact" clearable hide-details /></v-col>
    <v-col cols="12" md="3"><v-text-field v-model="filters.period" label="Review period" variant="outlined" density="compact" clearable hide-details /></v-col>
    <v-col cols="12" md="2"><v-select v-model="filters.status" :items="['Draft', 'Completed']" label="Status" variant="outlined" density="compact" clearable hide-details /></v-col>
    <v-col cols="12"><v-card><v-data-table :headers="headers" :items="filteredReviews" :items-per-page="10"><template #item.score="{ item }"><v-chip :color="ratingColor(item.rating)" size="small">{{ item.score }}% · {{ item.rating }}</v-chip></template><template #item.status="{ item }"><v-chip :color="item.status === 'Completed' ? 'success' : 'warning'" size="small">{{ item.status }}</v-chip></template><template #item.actions="{ item }"><v-btn icon="mdi-pencil" variant="text" size="small" color="primary" @click="openReview(item)" /><v-btn icon="mdi-delete-outline" variant="text" size="small" color="error" @click="remove(item)" /></template><template #no-data><div class="pa-8 text-center text-medium-emphasis">No performance reviews match these filters.</div></template></v-data-table></v-card></v-col>
  </v-row>

  <v-dialog v-model="dialog" max-width="1050" persistent scrollable><v-card><v-card-title class="pa-6 pb-2">{{ review.id ? 'Edit performance review' : 'New performance review' }}</v-card-title><v-card-text><v-row><v-col cols="12" md="5"><v-select v-model="review.employeeid" :items="employeeOptions" item-title="title" item-value="value" label="Employee" variant="outlined" :rules="[required]" /></v-col><v-col cols="12" md="3"><v-text-field v-model="review.period" label="Review period (e.g. Q3 2026)" variant="outlined" :rules="[required]" /></v-col><v-col cols="12" md="2"><v-select v-model="review.status" :items="['Draft', 'Completed']" label="Status" variant="outlined" /></v-col><v-col cols="12" md="2"><v-text-field :model-value="`${score}%`" label="Overall score" variant="outlined" readonly /></v-col></v-row>
    <div class="d-flex align-center justify-space-between mb-3"><div><div class="text-subtitle-1 font-weight-bold">KPI scorecard</div><div class="text-caption text-medium-emphasis">Scores are weighted automatically. Each KPI is stored as a snapshot with this review.</div></div><v-btn v-if="review.employeeid" variant="tonal" color="primary" prepend-icon="mdi-plus" @click="kpiPicker = true">Add KPI</v-btn></div>
    <v-alert v-if="!review.items.length" type="warning" variant="tonal" class="mb-4">No KPIs are in this scorecard. Select an employee, then add applicable active KPIs.</v-alert>
    <v-table v-else density="comfortable"><thead><tr><th>KPI</th><th>Target</th><th>Weight</th><th style="width: 170px">Actual result</th><th style="width: 130px">Score (%)</th><th></th></tr></thead><tbody><tr v-for="item in review.items" :key="item.kpiId"><td><div class="font-weight-medium">{{ item.name }}</div><div class="text-caption text-medium-emphasis">{{ item.description }}</div></td><td>{{ item.target }} {{ item.unit }}</td><td>{{ item.weight }}%</td><td><v-text-field v-model="item.actual" density="compact" variant="outlined" hide-details /></td><td><v-text-field v-model.number="item.score" type="number" min="0" max="100" density="compact" variant="outlined" hide-details /></td><td><v-btn icon="mdi-close" size="small" variant="text" color="error" @click="removeKpi(item.kpiId)" /></td></tr></tbody></v-table>
    <v-row class="mt-2"><v-col cols="12" md="8"><v-textarea v-model="review.managerComments" label="Manager comments and development actions" variant="outlined" rows="3" /></v-col><v-col cols="12" md="4"><v-card variant="tonal" color="primary" class="pa-4"><div class="text-caption">Performance rating</div><div class="text-h5 font-weight-bold">{{ rating }}</div><div class="text-body-2">Weighted score: {{ score }}%</div></v-card></v-col></v-row>
  </v-card-text><v-card-actions class="pa-6 pt-2"><v-spacer /><v-btn @click="dialog = false">Cancel</v-btn><v-btn color="primary" :disabled="!canSave" @click="save">Save review</v-btn></v-card-actions></v-card></v-dialog>

  <v-dialog v-model="kpiPicker" max-width="620"><v-card><v-card-title class="pa-5 pb-2">Add KPI to scorecard</v-card-title><v-card-subtitle>Only active KPIs that are not already included are shown.</v-card-subtitle><v-list class="px-3 pb-3"><v-list-item v-for="kpi in availableKpis" :key="kpi.id" :title="kpi.name" :subtitle="`${kpi.target} ${kpi.unit} · ${kpi.weight}% weight`" rounded="lg"><template #append><v-btn size="small" color="primary" variant="tonal" @click="addKpi(kpi)">Add</v-btn></template></v-list-item><v-list-item v-if="!availableKpis.length" title="No other active KPIs available" /></v-list></v-card></v-dialog>
</template>

<script setup>
import { computed, onMounted, ref, watch } from 'vue';
import { useEmployeeStore } from '../../stores/employeeStore';
import { useRoute } from 'vue-router';
const employeeStore = useEmployeeStore(); const route = useRoute(); const dialog = ref(false); const kpiPicker = ref(false); const filters = ref({ employeeid: null, department: null, period: '', status: null });
const emptyReview = () => ({ id: '', employeeid: '', employeeName: '', department: '', designation: '', period: '', status: 'Draft', score: 0, rating: '', managerComments: '', items: [] });
const review = ref(emptyReview());
const headers = [{ title: 'Employee', key: 'employeeName' }, { title: 'Department', key: 'department' }, { title: 'Period', key: 'period' }, { title: 'Score', key: 'score' }, { title: 'Status', key: 'status' }, { title: 'Actions', key: 'actions', sortable: false }];
const departments = computed(() => [...new Set(employeeStore.employees.map(e => e.department).filter(Boolean))].sort());
const employeeOptions = computed(() => employeeStore.employees.map(e => ({ title: `${e.name} (${e.employeeid})`, value: e.employeeid })));
const activeKpis = computed(() => employeeStore.kpis.filter(kpi => kpi.status === 'Active'));
const completedCount = computed(() => employeeStore.performanceReviews.filter(review => review.status === 'Completed').length);
const filteredReviews = computed(() => employeeStore.performanceReviews.filter(r => (!filters.value.employeeid || r.employeeid === filters.value.employeeid) && (!filters.value.department || r.department === filters.value.department) && (!filters.value.period || r.period.toLowerCase().includes(filters.value.period.toLowerCase())) && (!filters.value.status || r.status === filters.value.status)));
const score = computed(() => { const totalWeight = review.value.items.reduce((sum, item) => sum + Number(item.weight || 0), 0); if (!totalWeight) return 0; return Math.round(review.value.items.reduce((sum, item) => sum + Number(item.score || 0) * Number(item.weight || 0), 0) / totalWeight); });
const ratingFor = value => value >= 90 ? 'Outstanding' : value >= 75 ? 'Exceeds expectations' : value >= 60 ? 'Meets expectations' : value >= 40 ? 'Needs improvement' : 'Unsatisfactory';
const rating = computed(() => ratingFor(score.value)); const ratingColor = value => ({ Outstanding: 'success', 'Exceeds expectations': 'primary', 'Meets expectations': 'info', 'Needs improvement': 'warning', Unsatisfactory: 'error' }[value] || 'grey'); const required = value => !!value || 'Field is required';
const canSave = computed(() => Boolean(review.value.employeeid && review.value.period?.trim() && review.value.items.length));
const availableKpis = computed(() => activeKpis.value.filter(kpi => !review.value.items.some(item => item.kpiId === kpi.id)));
const kpiItem = kpi => ({ kpiId: kpi.id, name: kpi.name, description: kpi.description, target: kpi.target, unit: kpi.unit, weight: Number(kpi.weight), actual: '', score: 0 });
const loadApplicableKpis = () => { const employee = employeeStore.getEmployeeById(review.value.employeeid); if (!employee) return; review.value.employeeName = employee.name; review.value.department = employee.department || ''; review.value.designation = employee.designation || ''; review.value.items = employeeStore.kpis.filter(k => k.status === 'Active' && (!k.department || k.department === employee.department) && (!k.role || k.role === employee.designation)).map(k => ({ kpiId: k.id, name: k.name, description: k.description, target: k.target, unit: k.unit, weight: Number(k.weight), actual: '', score: 0 })); };
watch(() => review.value.employeeid, (id, old) => { if (id && id !== old && !review.value.id) loadApplicableKpis(); });
const addKpi = kpi => { review.value.items.push(kpiItem(kpi)); kpiPicker.value = false; };
const removeKpi = id => { review.value.items = review.value.items.filter(item => item.kpiId !== id); };
const openReview = (item) => { review.value = item ? { ...item, items: item.items.map(i => ({ ...i })) } : emptyReview(); kpiPicker.value = false; dialog.value = true; };
const save = () => { review.value.score = score.value; review.value.rating = rating.value; review.value.id ? employeeStore.updatePerformanceReview(review.value) : employeeStore.addPerformanceReview(review.value); employeeStore.callNotification({ text: 'Performance review saved', color: 'success' }); dialog.value = false; };
const remove = item => { if (window.confirm(`Delete the ${item.period} review for ${item.employeeName}?`)) { employeeStore.deletePerformanceReview(item.id); employeeStore.callNotification({ text: 'Performance review deleted', color: 'success' }); } };
onMounted(() => { employeeStore.load(); const id = route.query.review; if (id) { const item = employeeStore.performanceReviews.find(review => review.id === id); if (item) openReview(item); } });
</script>

<style scoped>
.performance-hero { background: linear-gradient(120deg, rgb(var(--v-theme-surface)) 0%, rgb(var(--v-theme-secondary)) 100%); }
</style>
